//! Placeholder sprite assets (self-made / CC0), generated by
//! `assets-tools/gen_placeholders.py` and embedded at build time so they load
//! identically on native and WASM. Swap for sourced art later without code changes.

use std::collections::HashMap;

use macroquad::prelude::*;

use crate::map::Tile;

pub struct Sprites {
    unit_textures: Vec<Texture2D>,
    unit_index: HashMap<String, usize>,
    ground: Texture2D,
    water: Texture2D,
    cliff: Texture2D,
    resource: Texture2D,
    pub selection: Texture2D,
}

fn tex(bytes: &[u8], filter: FilterMode) -> Texture2D {
    let t = Texture2D::from_file_with_format(bytes, Some(ImageFormat::Png));
    t.set_filter(filter);
    t
}

impl Sprites {
    pub fn load() -> Self {
        let units: [(&str, &[u8]); 6] = [
            ("infantry", include_bytes!("../assets/sprites/infantry.png")),
            ("engineer", include_bytes!("../assets/sprites/engineer.png")),
            ("tank", include_bytes!("../assets/sprites/tank.png")),
            ("artillery", include_bytes!("../assets/sprites/artillery.png")),
            ("aa", include_bytes!("../assets/sprites/aa.png")),
            ("truck", include_bytes!("../assets/sprites/truck.png")),
        ];
        let mut unit_textures = Vec::new();
        let mut unit_index = HashMap::new();
        for (name, bytes) in units {
            unit_index.insert(name.to_string(), unit_textures.len());
            unit_textures.push(tex(bytes, FilterMode::Linear));
        }

        Self {
            unit_textures,
            unit_index,
            ground: tex(include_bytes!("../assets/sprites/tile_ground.png"), FilterMode::Nearest),
            water: tex(include_bytes!("../assets/sprites/tile_water.png"), FilterMode::Nearest),
            cliff: tex(include_bytes!("../assets/sprites/tile_cliff.png"), FilterMode::Nearest),
            resource: tex(include_bytes!("../assets/sprites/tile_resource.png"), FilterMode::Nearest),
            selection: tex(include_bytes!("../assets/sprites/selection.png"), FilterMode::Linear),
        }
    }

    /// Sprite index for a unit sprite name (falls back to 0 if unknown).
    pub fn unit_index(&self, name: &str) -> usize {
        *self.unit_index.get(name).unwrap_or(&0)
    }

    pub fn unit_texture(&self, idx: usize) -> &Texture2D {
        &self.unit_textures[idx.min(self.unit_textures.len() - 1)]
    }

    pub fn tile(&self, t: Tile) -> &Texture2D {
        match t {
            Tile::Ground => &self.ground,
            Tile::Water => &self.water,
            Tile::Cliff => &self.cliff,
            Tile::Resource => &self.resource,
        }
    }
}
