//! Placeholder sprite atlas (self-made / CC0), generated by
//! `assets-tools/gen_placeholders.py` and embedded at build time. One atlas texture
//! plus source rects, so every sprite draw uses the same texture and batches into a
//! handful of GPU draw calls regardless of unit count.

use std::collections::HashMap;

use macroquad::prelude::*;

use crate::map::Tile;

const CELL: f32 = 64.0;
const COLS: usize = 4;

// Fixed atlas slot order — MUST match assets-tools/gen_placeholders.py.
const UNIT_ORDER: [&str; 6] = ["infantry", "engineer", "tank", "artillery", "aa", "truck"];
const SLOT_GROUND: usize = 6;
const SLOT_WATER: usize = 7;
const SLOT_CLIFF: usize = 8;
const SLOT_RESOURCE: usize = 9;
const SLOT_SELECTION: usize = 10;

fn slot_rect(i: usize) -> Rect {
    Rect::new((i % COLS) as f32 * CELL, (i / COLS) as f32 * CELL, CELL, CELL)
}

pub struct Sprites {
    pub atlas: Texture2D,
    unit_index: HashMap<String, usize>,
}

impl Sprites {
    pub fn load() -> Self {
        let atlas = Texture2D::from_file_with_format(
            include_bytes!("../assets/sprites/atlas.png"),
            Some(ImageFormat::Png),
        );
        // Nearest avoids sampling neighbouring atlas cells at sprite edges.
        atlas.set_filter(FilterMode::Nearest);

        let mut unit_index = HashMap::new();
        for (i, name) in UNIT_ORDER.iter().enumerate() {
            unit_index.insert((*name).to_string(), i);
        }
        Self { atlas, unit_index }
    }

    /// Slot index for a unit sprite name (falls back to 0 if unknown).
    pub fn unit_index(&self, name: &str) -> usize {
        *self.unit_index.get(name).unwrap_or(&0)
    }

    pub fn unit_rect(&self, idx: usize) -> Rect {
        slot_rect(idx.min(UNIT_ORDER.len() - 1))
    }

    pub fn tile_rect(&self, t: Tile) -> Rect {
        slot_rect(match t {
            Tile::Ground | Tile::Chokepoint => SLOT_GROUND,
            Tile::Water | Tile::River | Tile::RiverCrossing => SLOT_WATER,
            Tile::Cliff | Tile::MountainPass => SLOT_CLIFF,
            Tile::OreBasin | Tile::OilField => SLOT_RESOURCE,
            Tile::Road => SLOT_GROUND,
        })
    }

    pub fn selection_rect(&self) -> Rect {
        slot_rect(SLOT_SELECTION)
    }
}
